### ISSUE TITLE
slimcop 'hangs' 

### ISSUE THREAD

**Issue by koenhandekyn** [r7kamura/slimcop#15]
running slimcop on my project (both views / view component folders) hangs in the following location.

(running on mac arm processor, m1 pro)

known issue?

versions - ruby 3.0.4, rails 7.0.4.1

```
❯ be slimcop app/components/**/*.slim
Inspecting 178 files
.C.C....CC.CC...CC..C..C..CC......C...C.CC..C.C.C..CCC.CC...CCCC.W.C..WWCC....C.CCCC..CCCCC.CCC....C......CCCCC..C..CC.CCC.CC.....CC.WCC..CC.CC..C.C.CCCC.C..C.W.CCC.C...CC.CCC



^CParallel execution interrupted, exiting ...
/Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:199:in `block in trap_interrupt': Interrupt (Interrupt)
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:224:in `value'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:224:in `map'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:224:in `block (2 levels) in in_threads'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:220:in `handle_interrupt'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:220:in `block in in_threads'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:219:in `handle_interrupt'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:219:in `in_threads'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:463:in `block in work_in_processes'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:178:in `kill_on_ctrl_c'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:462:in `work_in_processes'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:294:in `map'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/templatecop-0.4.0/lib/templatecop/runner.rb:80:in `run_in_parallel'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/templatecop-0.4.0/lib/templatecop/runner.rb:34:in `call'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/templatecop-0.4.0/lib/templatecop/cli.rb:79:in `call'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/templatecop-0.4.0/lib/templatecop/cli.rb:38:in `call'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/slimcop-0.17.1/exe/slimcop:8:in `<top (required)>'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/bin/slimcop:25:in `load'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/bin/slimcop:25:in `<top (required)>'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/lib/bundler/cli.rb:491:in `exec'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/lib/bundler/cli.rb:28:in `start'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/exe/bundle:45:in `block in <top (required)>'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.2/exe/bundle:33:in `<top (required)>'
	from /Users/koenhandekyn/.rbenv/versions/3.0.4/bin/bundle:23:in `load'
	from /Users/k
```

**Comment by r7kamura** [comment]
Thanks for reporting back. This is the first time I see this type of problem. Can you identify what content Slim file is causing it?
