### ISSUE TITLE
Slimcop errors out whilie running

### ISSUE THREAD

**Issue by zoras** [r7kamura/slimcop#21]
```[bash]
$ slimcop
Inspecting 3427 files
....W.............Traceback (most recent call last):
	46: from ~/.asdf/installs/ruby/2.7.5/bin/slimcop:25:in `<main>'
	45: from ~/.asdf/installs/ruby/2.7.5/bin/slimcop:25:in `load'
	44: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/slimcop-0.19.1/exe/slimcop:8:in `<top (required)>'
	43: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/templatecop-0.4.0/lib/templatecop/cli.rb:38:in `call'
	42: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/templatecop-0.4.0/lib/templatecop/cli.rb:79:in `call'
	41: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/templatecop-0.4.0/lib/templatecop/runner.rb:34:in `call'
	40: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/templatecop-0.4.0/lib/templatecop/runner.rb:80:in `run_in_parallel'
	39: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/parallel-1.23.0/lib/parallel.rb:291:in `map'
	38: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/parallel-1.23.0/lib/parallel.rb:497:in `work_in_processes'
	37: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/parallel-1.23.0/lib/parallel.rb:558:in `create_workers'
	36: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/parallel-1.23.0/lib/parallel.rb:558:in `each_with_index'
	35: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/parallel-1.23.0/lib/parallel.rb:558:in `each'
	34: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/parallel-1.23.0/lib/parallel.rb:559:in `block in create_workers'
	33: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/parallel-1.23.0/lib/parallel.rb:568:in `worker'
	32: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/parallel-1.23.0/lib/parallel.rb:568:in `fork'
	31: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/parallel-1.23.0/lib/parallel.rb:577:in `block in worker'
	30: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/parallel-1.23.0/lib/parallel.rb:597:in `process_incoming_jobs'
	29: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/parallel-1.23.0/lib/parallel.rb:627:in `call_with_index'
	28: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/templatecop-0.4.0/lib/templatecop/runner.rb:82:in `block in run_in_parallel'
	27: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/templatecop-0.4.0/lib/templatecop/runner.rb:82:in `times'
	26: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/templatecop-0.4.0/lib/templatecop/runner.rb:85:in `block (2 levels) in run_in_parallel'
	25: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/templatecop-0.4.0/lib/templatecop/runner.rb:75:in `investigate'
	24: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/templatecop-0.4.0/lib/templatecop/template_offense_collector.rb:30:in `call'
	23: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/templatecop-0.4.0/lib/templatecop/template_offense_collector.rb:52:in `snippets'
	22: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/slimcop-0.19.1/lib/slimcop/ruby_extractor.rb:19:in `call'
	21: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/slimcop-0.19.1/lib/slimcop/ruby_extractor.rb:32:in `call'
	20: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/slimcop-0.19.1/lib/slimcop/ruby_extractor.rb:53:in `ranges'
	19: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/slimcop-0.19.1/lib/slimcop/ruby_extractor.rb:45:in `ast'
	18: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:45:in `call'
	17: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:49:in `compile'
	16: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:112:in `dispatcher'
	15: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:7:in `on_multi'
	14: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:7:in `each'
	13: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:7:in `block in on_multi'
	12: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:49:in `compile'
	11: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:97:in `dispatcher'
	10: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/html/dispatcher.rb:27:in `on_html_tag'
	 9: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:49:in `compile'
	 8: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:80:in `dispatcher'
	 7: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/slimi-0.7.4/lib/slimi/filters/base.rb:45:in `on_slimi_text'
	 6: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:49:in `compile'
	 5: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:112:in `dispatcher'
	 4: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:7:in `on_multi'
	 3: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:7:in `each'
	 2: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:7:in `block in on_multi'
	 1: from ~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:49:in `compile'
~/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/temple-0.8.2/lib/temple/mixins/dispatcher.rb:66:in `dispatcher': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by r7kamura** [comment]
Thanks for your reporting @zoras 👍 

It seems that the error is occurring from the Slim template parser, [slimi](https://github.com/r7kamura/slimi), used in the internal implementation of slimcop.
Can you tell me the content of the slim template that is actually causing the problem?

**Comment by r7kamura** [comment]
I'll ransfer this Issue to slimi repository for the same reason as the following Issue:

- https://github.com/r7kamura/slimi/issues/14
